#!/usr/bin/env bash
##########################################################################
# If not stated otherwise in this file or this component's LICENSE
# file the following copyright and licenses apply:
#
# Copyright 2024 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###########################################################################

# Save _TOPDIR
_TOPDIR=`pwd`

export RDK_BSP_LAYER=none

#select filogic880-bpi-r4.conf for BPI R4
if [ -e "${_TOPDIR}/meta-cmf-filogic/setup-environment-release" ]; then
	source meta-cmf-filogic/setup-environment-release
fi


if [[ -z $(grep 'meta-cmf-bananapi' conf/bblayers.conf) ]] && [[ -d  ../meta-cmf-bananapi ]]
then
    cat >> conf/bblayers.conf <<EOF
BBLAYERS =+ "\${RDKROOT}/meta-cmf-bananapi"
EOF
fi

# default BSP layer is meta-cmf-bananapi for B-PI builds
export RDK_BSP_LAYER=meta-cmf-bananapi


# Enabling distro features as part of the build
if [ "X$BPI_IMG_TYPE" != "X" ]; then
    echo "DISTRO_FEATURES_append =\" $BPI_IMG_TYPE\"" >> conf/local.conf
fi
