#@TYPE: Machine
#@NAME: bananapi4-rdk-broadband-ap-extender
#@NEEDED_BSPLAYERS: meta-cmf-bananapi
#@DESCRIPTION: Machine configuration for running a RDK broadband on Banana Pi R4
#@RDK_FLAVOR: rdkb

RUST_PANIC_STRATEGY="abort"

require conf/machine/filogic880-bpi-r4.conf
DISTRO_FEATURES_append = " em_extender"
require conf/distro/include/rdk-bpi-ap-extender.inc 
PREFERRED_PROVIDER_hal-wifi_onewifi = "hal-wifi-generic"
MACHINE_IMAGE_NAME = "rdk-generic-ap-extender-image"

#SDCARD supported changes.
MACHINEOVERRIDES .="${@bb.utils.contains('DISTRO_FEATURES','sdmmc',':sd','',d)}"
IMAGE_FSTYPES += "${@bb.utils.contains('DISTRO_FEATURES','sdmmc','wic.bz2 ext4','',d)}"
KERNEL_DEVICETREE_mt7988_bpi4_sd = "mediatek/mt7988a-bananapi-bpi-r4-sd.dtb"

WKS_FILE = " ${@bb.utils.contains('DISTRO_FEATURES','EasyMesh',' sdimage-EM-Bananapi.wks',' sdimage-Bananapi.wks',d)}"
IMAGE_BOOT_FILES = "${@bb.utils.contains('DISTRO_FEATURES','sdmmc','mt7988a-bananapi-bpi-r4-sd.dtb ${KERNEL_IMAGETYPE}','',d)}"
do_image_wic[recrdeps] = "do_build"
#SDCARD supported Pre build bootloader
do_image_wic[depends] += " atf_bootloader_prebuild:do_deploy"
