#@TYPE: Machine
#@NAME: bananapi4-rdk-broadband
#@NEEDED_BSPLAYERS: meta-cmf-bananapi
#@DESCRIPTION: Machine configuration for running a RDK broadband on Banana Pi R4
#@RDK_FLAVOR: rdkb

require conf/machine/filogic880-bpi-r4.conf

require conf/distro/include/rdk-bpi.inc 
PREFERRED_PROVIDER_hal-wifi_onewifi = "hal-wifi-generic"

#SDCARD supported changes.
MACHINEOVERRIDES .="${@bb.utils.contains('DISTRO_FEATURES','sdmmc',':sd','',d)}"
IMAGE_FSTYPES += "${@bb.utils.contains('DISTRO_FEATURES','sdmmc',' wic.bz2 ext4','',d)}"
KERNEL_DEVICETREE_mt7988_bpi4_sd = "mediatek/mt7988a-bananapi-bpi-r4-sd.dtb"

WKS_FILE = " sdimage-Bananapi.wks"
IMAGE_BOOT_FILES = "${@bb.utils.contains('DISTRO_FEATURES','sdmmc','mt7988a-bananapi-bpi-r4-sd.dtb ${KERNEL_IMAGETYPE}','',d)}"
do_image_wic[recrdeps] = "do_build"
#SDCARD supported Pre build bootloader
do_image_wic[depends] += " atf_bootloader_prebuild:do_deploy"
