BBPATH .= ":${LAYERDIR}"
BBFILES += "\
            ${LAYERDIR}/meta*/recipes-*/*/*.bb \
            ${LAYERDIR}/meta*/recipes-*/*/*.bbappend \
            ${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend \
           "

BBFILE_COLLECTIONS += "cmf-bananapi"
BBFILE_PATTERN_cmf-bananapi := "^${LAYERDIR}/"

LAYERDEPENDS_cmf-bananapi = "cmf-filogic"
LAYERDEPENDS_cmf-bananapi:append = " filogic"


LAYERSERIES_COMPAT_cmf-bananapi = " kirkstone wrynose"

MIDDLEWARE_ARCH = "${MACHINE}"
PACKAGE_EXTRA_ARCHS:append = " ${MIDDLEWARE_ARCH}"
